const services = [
  {
    icon: (
      <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" />
      </svg>
    ),
    title: "Comprehensive Eye Examination",
    desc: "Full clinical eye assessment using advanced testing protocols to evaluate visual acuity and refractive errors.",
  },
  {
    icon: (
      <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9.75 17L9 20l-1 1h8l-1-1-.75-3M3 13h18M5 17h14a2 2 0 002-2V5a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
      </svg>
    ),
    title: "Computerised Eye Testing",
    desc: "Precision prescriptions generated by modern auto-refractometers for high accuracy lenses.",
  },
  {
    icon: (
      <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
      </svg>
    ),
    title: "Contact Lens Fitting & Fitting",
    desc: "Personalized fitting, lifestyle guidance, and full handling training for soft, toric, and colored contact lenses.",
  },
  {
    icon: (
      <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 3H5a2 2 0 00-2 2v4m6-6h10a2 2 0 012 2v4M9 3v18m0 0h10a2 2 0 002-2V9M9 21H5a2 2 0 01-2-2V9m0 0h18" />
      </svg>
    ),
    title: "Progressive Lens Consultation",
    desc: "Step-by-step guidance for adaptively transitioning to multi-focal progressive glasses.",
  },
  {
    icon: (
      <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z" />
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
      </svg>
    ),
    title: "Frame Repair & Maintenance",
    desc: "Instant nosepad replacement, customized adjustments, temple soldering, and ultrasonic frame alignment.",
  },
  {
    icon: (
      <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 8v13m0-13V6a2 2 0 112 2h-2zm0 0V5.5A2.5 2.5 0 109.5 8H12zm-7 4h14M5 12a2 2 0 110-4h14a2 2 0 110 4M5 12v7a2 2 0 002 2h10a2 2 0 002-2v-7" />
      </svg>
    ),
    title: "Premium Lens Customization",
    desc: "Lens matching using digital measurements to coordinate index sizes with frame shapes.",
  },
  {
    icon: (
      <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" />
      </svg>
    ),
    title: "Courier & Home Delivery",
    desc: "Prompt delivery within local regions and secured shipping to destinations across India.",
  },
  {
    icon: (
      <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />
      </svg>
    ),
    title: "Professional Guarantee Support",
    desc: "Full assistance for product warranties, coating inspections, and long-term adjustments.",
  },
];

export default function Services() {
  return (
    <section id="services" className="py-24 md:py-32 bg-white relative">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        
        {/* Section Header */}
        <div className="text-center mb-16 md:mb-24">
          <span className="section-subtitle-premium">What We Do</span>
          <h2 className="section-title-premium mt-2">
            Professional Services
          </h2>
          <p className="text-slate-500 max-w-xl mx-auto mt-4 text-base sm:text-lg">
            From clinical vision analysis to custom frame adjustments — complete optical excellence under one roof.
          </p>
        </div>

        {/* Services Grid */}
        <div className="grid sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
          {services.map((s) => (
            <div
              key={s.title}
              className="group p-8 bg-slate-50 hover:bg-[#070b13] rounded-3xl transition-all duration-500 border border-slate-100 hover:border-ruby-900/50 hover:shadow-premium-glow hover:-translate-y-1 cursor-default flex flex-col"
            >
              {/* Icon Container */}
              <div className="w-12 h-12 bg-white group-hover:bg-ruby-600 rounded-2xl flex items-center justify-center text-ruby-700 group-hover:text-white transition-all duration-500 mb-6 shadow-sm border border-slate-100 group-hover:border-transparent">
                {s.icon}
              </div>
              
              {/* Service Title */}
              <h3 className="font-display font-extrabold text-base text-navy-900 group-hover:text-white leading-snug mb-3 transition-colors duration-500">
                {s.title}
              </h3>
              
              {/* Service Description */}
              <p className="text-sm text-slate-500 group-hover:text-slate-400 leading-relaxed transition-colors duration-500">
                {s.desc}
              </p>
            </div>
          ))}
        </div>

        {/* Premium Warranty Callout */}
        <div className="mt-16 bg-gradient-to-r from-navy-950 via-ruby-950 to-navy-900 rounded-[32px] p-8 md:p-12 text-white border border-white/5 relative overflow-hidden shadow-2xl flex flex-col lg:flex-row items-center gap-8">
          {/* Subtle glow background */}
          <div className="absolute top-0 right-0 w-80 h-80 bg-ruby-700/10 rounded-full blur-[80px] pointer-events-none" />

          {/* Badge Visual */}
          <div className="flex-shrink-0 w-20 h-20 bg-white/5 border border-white/10 rounded-2xl flex items-center justify-center relative shadow-inner">
            <svg className="w-10 h-10 text-gold-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />
            </svg>
            <span className="absolute -bottom-1 -right-1 flex h-4 w-4">
              <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-gold-400 opacity-75"></span>
              <span className="relative inline-flex rounded-full h-4 w-4 bg-gold-500"></span>
            </span>
          </div>

          {/* Text Content */}
          <div className="flex-1 text-center lg:text-left space-y-2">
            <span className="text-gold-400 text-xs font-bold uppercase tracking-widest bg-gold-950/40 border border-gold-900/30 px-3 py-1 rounded-md">
              Client Guarantee
            </span>
            <h3 className="font-display text-2xl font-extrabold text-white mt-2">1-Year Manufacturing Warranty</h3>
            <p className="text-slate-400 text-sm max-w-3xl leading-relaxed">
              Every single pair of spectacles and ophthalmic lenses purchased at Ruby Opticals is protected by a 12-month manufacturer guarantee. Our support continues throughout your product lifecycle with free adjustments.
            </p>
          </div>

          {/* Call-to-action button */}
          <a
            href="#contact"
            className="flex-shrink-0 btn-premium-gold"
          >
            Learn More
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M9 5l7 7-7 7" />
            </svg>
          </a>
        </div>

      </div>
    </section>
  );
}

